#!/bin/bash

. "${SNAP}/actions/common/utils.sh"

if ! is_strict || (is_strict && snapctl is-connected network-control)
then
  for link in cni0
  do
    if "${SNAP}/sbin/ip" link show "${link}"
    then
      "${SNAP}/sbin/ip" link delete "${link}" || true
    fi
  done
  for calink in $("${SNAP}/sbin/ip" -j --pretty link show |\
                 awk '/cali/ {print $2}' | tr -d '",')
  do "${SNAP}/sbin/ip" link delete "${calink}"
  done
fi
