#!/bin/bash

. "${SNAP}/actions/common/utils.sh"

if ! is_strict || (is_strict && snapctl is-connected network-control)
then
  for link in cni0 vxlan.calico
  do
    if "${SNAP}/sbin/ip" link show "${link}"
    then
      "${SNAP}/sbin/ip" link delete "${link}" || true
    fi
  done
fi

if ! is_strict || (is_strict && snapctl is-connected network-control)
then
  for workloadendpoint in cat "${SNAP_DATA}"/.workload_endpoints
  do
    if "${SNAP}/sbin/ip" link show "${workloadendpoint}"
    then
      "${SNAP}/sbin/ip" link delete "${workloadendpoint}" || true
    fi
  done
fi
