#!/bin/bash

set -eu

export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"
export LD_LIBRARY_PATH="$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu"
export LD_LIBRARY_PATH=$SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH

source $SNAP/actions/common/utils.sh

restart_attempt=0
while true
do
    if [ $restart_attempt -ge 5 ]
    then
        echo "Service kicker restarted the apiserver too quickly. Exiting."
        exit 1
    fi

    # every 3 seconds
    sleep 3
    if [ -f "${SNAP_DATA}/external_ip.txt" ] &&
       ! grep -E "(--advertise-address|--bind-address)" $SNAP_DATA/args/kube-apiserver &> /dev/null &&
       ip route | grep default &> /dev/null &&
       systemctl is-active --quiet snap.microk8s.daemon-apiserver.service
    then
        IP_ADDR="$(get_ips)"
        USED_IP_ADDR="$(cat "${SNAP_DATA}"/external_ip.txt)"
        if ! [ "$IP_ADDR" == "$USED_IP_ADDR" ]
        then
            echo "IP change detected. Reconfiguring the kube-apiserver"
            produce_server_cert $IP_ADDR
            rm -rf .srl

            systemctl restart snap.microk8s.daemon-containerd.service
            systemctl restart snap.microk8s.daemon-apiserver.service
            systemctl restart snap.microk8s.daemon-proxy.service
            systemctl restart snap.microk8s.daemon-kubelet.service
            restart_attempt=$[$restart_attempt+1]
        else
            restart_attempt=0
        fi
    fi
done
