#!/bin/bash
set -ex
export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"

if [ -e ${SNAP_DATA}/var/lock/lite.lock ]
then
  echo "Will not run along with kubelite"
  exit 0
else
  echo "Service should not be running. This is a single binary snap"
  exit 1
fi
