#!/bin/bash
set -e
export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu"
export LD_LIBRARY_PATH=$SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH

# wait for docker socker
if grep -e "-H " $SNAP_DATA/args/dockerd &> /dev/null
then
  socket=$(grep -e "-H " $SNAP_DATA/args/dockerd | awk '{print $2}')
  socket_file=${socket#"unix://"}
  # socket_file may be of the form ${SNAP_DATA}/docker.sock
  # we need to replace any variables
  socket_file_expand=$(eval echo ${socket_file})

  # wait up until 20 seconds for the docker socket to appear
  n=0
  until [ $n -ge 10 ]
  do
    test -S "${socket_file_expand}" && break
    echo "Waiting for docker socket ${socket_file_expand} to appear. (attempt $n)"
    n=$[$n+1]
    sleep 2
  done
fi

app="kubelet"

# This is really the only way I could find to get the args passed in correctly. WTF
declare -a args="($(cat $SNAP_DATA/args/$app))"
if [ -f $SNAP/$app ]
then
  exec "$SNAP/$app" "${args[@]}"
else
  # dockerd is not in $SNAP
  exec "$SNAP/usr/bin/$app" "${args[@]}"
fi
