#!/bin/bash
set -ex
export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"
ARCH="$($SNAP/bin/uname -m)"
export LD_LIBRARY_PATH="$SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/$ARCH-linux-gnu:$SNAP/usr/lib/$ARCH-linux-gnu"

source $SNAP/actions/common/utils.sh

if ! [ -e "$SNAP_DATA/var/lock/clustered.lock" ]; then
  echo "Not a worker node, exiting"
  exit 0
fi

if ! [ -e "$SNAP_DATA/args/traefik" ]
then
  exit 0
fi

if ! [ -e "$SNAP_DATA/args/apiserver-proxy" ]
then
  exit 0
fi

sed 's@${SNAP}@'"${SNAP}"'@g;s@${SNAP_DATA}@'"${SNAP_DATA}"'@g' $SNAP_DATA/args/traefik/traefik-template.yaml > $SNAP_DATA/args/traefik/traefik.yaml

set -a
if [ -e ${SNAP_DATA}/args/fips-env ]
then
  . ${SNAP_DATA}/args/fips-env
fi
set +a

# This is really the only way I could find to get the args passed in correctly.
declare -a args="($(cat $SNAP_DATA/args/apiserver-proxy))"
exec "$SNAP/bin/cluster-agent" apiserver-proxy "${args[@]}"
