# Help documentation when the registry hasn't been installed
# Allows tools to tell users how to enable the registry.
# https://github.com/kubernetes/enhancements/issues/1755
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
data:
  localRegistryHosting.v1: |
    help: "https://microk8s.io/docs/registry-built-in"
