name: Prepare test prerequisites

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install test dependencies
      shell: bash
      run: |
        set -x
        sudo pip3 install -U pytest==8.3.4 sh psutil requests
    # Docker sets iptables rules that interfere with LXD and K8s.
    # https://documentation.ubuntu.com/lxd/en/latest/howto/network_bridge_firewalld/#prevent-connectivity-issues-with-lxd-and-docker
    - name: Apply Docker iptables workaround
      shell: bash
      run: sudo iptables -I DOCKER-USER -j ACCEPT
    - name: Fetch snap
      uses: actions/download-artifact@v4
      with:
        name: microk8s.snap
        path: build
