#!/bin/bash

. "${SNAP}/actions/common/utils.sh"

KUBECTL="${SNAP}/microk8s-kubectl.wrapper"

# Cilium reload deployment
if ! [ -e "${SNAP_DATA}/var/lock/no-cni-reload" ] &&
   ! [ -e "${SNAP_DATA}/args/cni-network/cni.yaml" ] &&
   [ -e "${SNAP_DATA}/var/lock/no-flanneld" ] &&
   [ -e "${SNAP_DATA}/var/lock/cni-needs-reload" ]
then
  echo "Reloading the cilium CNI"
  if (is_apiserver_ready)  &&
      "${KUBECTL}" --request-timeout 2m describe -n kube-system daemonset.apps/cilium &&
      "${KUBECTL}" --request-timeout 2m describe -n kube-system deployment.apps/cilium-operator &&
      "${KUBECTL}" --request-timeout 2m rollout restart -n kube-system daemonset.apps/cilium  &&
      "${KUBECTL}" --request-timeout 2m rollout restart -n kube-system deployment.apps/cilium-operator
  then
    rm "${SNAP_DATA}/var/lock/cni-needs-reload"
  fi
fi
