#!/bin/bash

. "${SNAP}/actions/common/utils.sh"

KUBECTL="${SNAP}/microk8s-kubectl.wrapper"

if ! [ -e "${SNAP_DATA}/var/lock/kube-apiserver-to-kubelet-roles" ]
then
  echo "Apply kube-apiserver to kubelet communication RBAC rules"
  mkdir -p "${SNAP_DATA}/args/manifests"
  if ! [ -e "${SNAP_DATA}/args/manifests/kube-apiserver-to-kubelet.yaml" ]
  then
    cp "${SNAP}/default-args/manifests/kube-apiserver-to-kubelet.yaml" "${SNAP_DATA}/args/manifests/kube-apiserver-to-kubelet.yaml"
  fi

  if (is_apiserver_ready) && "${KUBECTL}" apply -f "${SNAP_DATA}/args/manifests/kube-apiserver-to-kubelet.yaml"
  then
    touch "${SNAP_DATA}/var/lock/kube-apiserver-to-kubelet-roles"
  fi
fi
