#!/bin/bash

. "${SNAP}/actions/common/utils.sh"

KUBECTL="${SNAP}/microk8s-kubectl.wrapper"

if [ -e "${SNAP_DATA}/args/cni-network/cni.yaml" ] &&
   [ -e "${SNAP_DATA}/var/lock/ha-cluster" ] &&
   ! [ -e "${SNAP_DATA}/var/lock/cni-loaded" ]
then
  echo "Setting up the CNI"
  if (is_apiserver_ready)
  then
    ENDPOINT=$("${KUBECTL}" get endpoints -o json | jq ".items[0].subsets[0].addresses[0].ip")
    $SNAP/bin/sed -i 's/SERVICEHOST/'"${ENDPOINT}"'/g' $SNAP_DATA/args/cni-network/kubernetes-services-endpoint.yaml
    "${KUBECTL}" apply -f "${SNAP_DATA}/args/cni-network/kubernetes-services-endpoint.yaml"
  fi
  if (is_apiserver_ready) && "${KUBECTL}" apply -f "${SNAP_DATA}/args/cni-network/cni.yaml"
  then
    touch "${SNAP_DATA}/var/lock/cni-loaded"
  fi
fi
