name: microk8s
adopt-info: kubernetes
summary: Kubernetes for workstations and appliances
description: |-
  MicroK8s is a small, fast, secure, single node Kubernetes that installs on
  just about any Linux box. Use it for offline development, prototyping,
  testing, or use it on a VM as a small, cheap, reliable k8s for CI/CD. It's
  also a great k8s for appliances - develop your IoT apps for k8s and deploy
  them to MicroK8s on your boxes.

grade: stable
confinement: classic
base: core18

apps:
  microk8s:
    command: microk8s.wrapper
    completer: microk8s.bash
  daemon-etcd:
    command: run-etcd-with-args
    daemon: simple
  daemon-flanneld:
    command: run-flanneld-with-args
    daemon: simple
  daemon-containerd:
    command: run-containerd-with-args
    daemon: notify
    # when stopped send only sigterm
    # https://forum.snapcraft.io/t/process-lifecycle-on-snap-refresh/140/37
    stop-mode: sigterm
    restart-condition: always
    plugs: [kubernetes-support]
  daemon-kubelite:
    command: run-kubelite-with-args
    daemon: simple
  daemon-apiserver:
    command: run-null-daemon
    daemon: simple
  daemon-apiserver-kicker:
    command: apiservice-kicker
    daemon: simple
  daemon-traefik:
    command: run-traefik-with-args
    daemon: simple
  daemon-control-plane-kicker:
    command: run-null-daemon
    daemon: simple
  daemon-cluster-agent:
    command: run-cluster-agent-with-args
    daemon: simple
  daemon-controller-manager:
    command: run-null-daemon
    daemon: simple
  daemon-scheduler:
    command: run-null-daemon
    daemon: simple
  daemon-kubelet:
    command: run-null-daemon
    daemon: simple
  daemon-proxy:
    command: run-null-daemon
    daemon: simple
  daemon-k8s-dqlite:
    command: run-k8s-dqlite-with-args
    daemon: simple
  dashboard-proxy:
    command: microk8s-dashboard-proxy.wrapper
  kubectl:
    command: microk8s-kubectl.wrapper
    completer: kubectl.bash
  add-node:
    command: microk8s-add-node.wrapper
  addons:
    command: microk8s-addons.wrapper
  refresh-certs:
    command: microk8s-refresh-certs.wrapper
  images:
    command: microk8s-images.wrapper
  join:
    command: microk8s-join.wrapper
  remove-node:
    command: microk8s-remove-node.wrapper
  leave:
    command: microk8s-leave.wrapper
  ctr:
    command: microk8s-ctr.wrapper
  inspect:
    command: microk8s.wrapper inspect
  enable:
    command: microk8s-enable.wrapper
  disable:
    command: microk8s-disable.wrapper
  start:
    command: microk8s-start.wrapper
  stop:
    command: microk8s-stop.wrapper
  status:
    command: microk8s-status.wrapper
  config:
    command: microk8s-config.wrapper
  reset:
    command: microk8s-reset.wrapper
  istioctl:
    command: microk8s-istioctl.wrapper
  linkerd:
    command: microk8s-linkerd.wrapper
  helm:
    command: microk8s-helm.wrapper
    completer: helm.bash
  helm3:
    command: microk8s-helm3.wrapper
    completer: helm3.bash
  cilium:
    command: microk8s-cilium.wrapper
  dbctl:
    command: microk8s-dbctl.wrapper
  version:
    command: microk8s-version.wrapper

parts:
  raft:
    source: https://github.com/canonical/raft
    source-tag: v0.13.0
    build-attributes: [no-patchelf]
    source-type: git
    plugin: autotools
    stage-packages:
      - libuv1
    build-packages:
      - liblz4-dev
    organize:
      usr/lib/: lib/
      include/: usr/include/
    prime:
      - lib/libraft*so*
      - usr/include/

  sqlite:
    source: https://github.com/sqlite/sqlite
    source-type: git
    source-depth: 1
    source-tag: version-3.33.0
    build-attributes: [no-patchelf]
    build-environment:
      - CFLAGS: "-DSQLITE_ENABLE_DBSTAT_VTAB=1"
    plugin: autotools
    build-packages:
      - tcl
    override-build: |-
      set -ex
      git log -1 --format=format:%ci%n | sed -e 's/ [-+].*$//;s/ /T/;s/^/D /' > manifest
      git log -1 --format=format:%H > manifest.uuid
      cp /usr/share/misc/config.guess .
      cp /usr/share/misc/config.sub .
      autoreconf -f -i
      set +ex
      snapcraftctl build
    organize:
      include/: usr/include/
    prime:
      - bin/sqlite3
      - lib/libsqlite3*so*
      - usr/include/

  dqlite:
    after: [raft, sqlite]
    source: https://github.com/canonical/dqlite
    source-tag: v1.10.0
    build-attributes: [no-patchelf]
    source-type: git
    plugin: autotools
    stage-packages:
      - libuv1
    build-packages:
      - libuv1-dev
      - pkg-config
    organize:
      usr/lib/: lib/
      include/: usr/include/
    prime:
      - lib/libdqlite*so*
      - lib/*/libuv*
      - usr/include/

  golang:
    plugin: nil
    override-build: |
      snap install go --classic
      snap refresh go --channel 1.18
    build-packages:
      - btrfs-tools
      - libseccomp-dev
      - rsync
      - build-essential
      - curl
      - git

  dqlite-client:
    after: [sqlite, dqlite, golang]
    plugin: nil
    source: build-scripts/
    override-build: ./build-component.sh dqlite-client

  k8s-dqlite:
    after: [dqlite-client, dqlite, golang]
    source: build-scripts/
    plugin: nil
    override-build: ./build-component.sh k8s-dqlite

  etcd:
    after: [golang]
    plugin: nil
    source: build-scripts/
    override-build: ./build-component.sh etcd

  traefik:
    after: [golang]
    plugin: nil
    source: build-scripts/
    override-build: ./build-component.sh traefik
    build-attributes: [no-patchelf]

  cni:
    after: [golang]
    plugin: nil
    source: build-scripts/
    override-build: ./build-component.sh cni

  flanneld:
    after: [golang]
    plugin: nil
    source: build-scripts/
    override-build: ./build-component.sh flanneld

  kubernetes:
    after: [golang]
    plugin: nil
    build-attributes: [no-patchelf]
    source: build-scripts/
    override-build: |
      ./build-component.sh kubernetes
      snapcraftctl set-version "$(components/kubernetes/version.sh)"

  helm:
    after: [golang]
    plugin: nil
    source: build-scripts/
    override-build: ./build-component.sh helm

  libmnl:
    plugin: autotools
    source: https://www.netfilter.org/pub/libmnl/libmnl-1.0.4.tar.bz2

  libnftnl:
    after:
      - libmnl
    plugin: autotools
    source: https://www.netfilter.org/projects/libnftnl/files/libnftnl-1.1.8.tar.bz2
    build-packages:
      - libjansson-dev

  iptables:
    after: [libnftnl]
    source: https://www.netfilter.org/projects/iptables/files/iptables-1.8.6.tar.bz2
    plugin: autotools
    build-packages:
      - bison
      - flex
      - libnfnetlink-dev
      - libnetfilter-conntrack3
      - libnetfilter-conntrack-dev
    configflags:
      - "--disable-shared"
      - "--enable-static"
    prime: [-bin/iptables-xml]

  migrator:
    after: [golang]
    plugin: nil
    source: build-scripts/
    override-build: ./build-component.sh migrator

  containerd:
    after: [golang, iptables, runc]
    plugin: nil
    source: build-scripts/
    override-build: ./build-component.sh containerd
    build-attributes: [no-patchelf]
    stage-packages:
      - libnss-myhostname
      - libnss-resolve
      - libnss-mymachines
      - conntrack
      - libssl1.0.0
    stage:
      - -sbin/xtables-multi
      - -sbin/iptables*
      - -lib/xtables
      - -usr/share/doc
      - -usr/share/man

  runc:
    build-snaps: [go]
    after: [iptables, golang]
    source: build-scripts/
    plugin: nil
    override-build: ./build-component.sh runc

  bash-utils:
    plugin: nil
    stage-packages:
      - aufs-tools
      - coreutils
      - curl
      - diffutils
      - ethtool
      - gawk
      - git
      - grep
      - hostname
      - iproute2
      - jq
      - kmod
      - libatm1
      - members
      - net-tools
      - openssl
      - sed
      - socat
      - squashfs-tools
      - tar
      - util-linux
      - zfsutils-linux
    stage:
      - -usr/share/doc
      - -usr/share/man

  cluster-agent:
    after: [golang]
    build-attributes: [no-patchelf]
    plugin: nil
    source: build-scripts/
    override-build: ./build-component.sh cluster-agent

  microk8s-addons:
    plugin: nil
    build-attributes: [no-patchelf]
    source: build-scripts/
    override-build: |
      set -eux

      . ./addon-repositories.sh

      if [ -d "${SNAPCRAFT_PART_INSTALL}" ]; then
        rm -rf "${SNAPCRAFT_PART_INSTALL}/*"
      fi
      if [ -d addons ]; then
        rm -rf addons
      fi

      IFS=';'
      echo "${ADDONS_REPOS}" | while read line; do
        if [ -z "${line}" ];
          then continue
        fi
        name="$(echo ${line} | cut -f1 -d',')"
        repository="$(echo ${line} | cut -f2 -d',')"
        reference="$(echo ${line} | cut -f3 -d',')"
        git clone "${repository}" -b "${reference}" "addons/${name}"
      done
      echo "${ADDONS_REPOS_ENABLED}" > addons/.auto-add

      cp -r "addons" "${SNAPCRAFT_PART_INSTALL}/addons"

  microk8s-scripts:
    plugin: nil
    source: scripts/
    override-build: |
      if [ -d "${SNAPCRAFT_PART_INSTALL}" ]; then
        rm -rf "${SNAPCRAFT_PART_INSTALL}/*"
      fi

      cp -r . "${SNAPCRAFT_PART_INSTALL}/scripts"
      cp inspect.sh "${SNAPCRAFT_PART_INSTALL}/inspect.sh"

  microk8s-upgrade-scripts:
    plugin: nil
    source: upgrade-scripts/
    override-build: |
      if [ -d "${SNAPCRAFT_PART_INSTALL}" ]; then
        rm -rf "${SNAPCRAFT_PART_INSTALL}/*"
      fi

      cp -r . "${SNAPCRAFT_PART_INSTALL}/upgrade-scripts"

  microk8s:
    plugin: nil
    source: microk8s-resources/
    override-build: |
      if [ -d "${SNAPCRAFT_PART_INSTALL}" ]; then
        rm -rf "${SNAPCRAFT_PART_INSTALL}/*"
      fi

      cp -r default-args "${SNAPCRAFT_PART_INSTALL}/default-args"
      cp -r default-hooks "${SNAPCRAFT_PART_INSTALL}/default-hooks"
      cp -r certs "${SNAPCRAFT_PART_INSTALL}/certs"
      cp -r certs-beta "${SNAPCRAFT_PART_INSTALL}/certs-beta"

      cp containerd-profile "${SNAPCRAFT_PART_INSTALL}/containerd-profile"

      cp client.config "${SNAPCRAFT_PART_INSTALL}/client.config"
      cp client.config.template "${SNAPCRAFT_PART_INSTALL}/client.config.template"
      cp kubelet.config.template "${SNAPCRAFT_PART_INSTALL}/kubelet.config.template"
      cp client-x509.config.template "${SNAPCRAFT_PART_INSTALL}/client-x509.config.template"

      cp -r wrappers/* "${SNAPCRAFT_PART_INSTALL}/"
      cp -r actions/ "${SNAPCRAFT_PART_INSTALL}/actions"

  microk8s-completion:
    after: [golang]
    plugin: nil
    source: build-scripts/
    override-build: ./build-component.sh microk8s-completion

  python-requirements:
    plugin: python
    python-version: python3
    python-packages:
      - PyYAML == 5.3.1
      - netifaces == 0.10.9
      - jsonschema == 4.0.0
    stage-packages:
      - python3-openssl
      - python3-requests
      - python3-click
      - python3-dateutil
    stage:
      - -usr/share/doc
      - -usr/share/man

slots:
  microk8s:
    interface: content
    content: microk8s
    source:
      read:
        - $SNAP_DATA/credentials
