#!/usr/bin/env bash
set -eux

ARCH="$($SNAP/bin/uname -m)"
export LD_LIBRARY_PATH="$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/$ARCH-linux-gnu:$SNAP/usr/lib/$ARCH-linux-gnu"
export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH:/usr/bin:/usr/local/bin"

for image in $(ls $SNAP_COMMON/images/*.tar); do
    $SNAP/microk8s-ctr.wrapper image import $SNAP_COMMON/images/$image
done
